import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Network, TrendingUp, ShieldCheck, MapPinned, Building, Handshake, Compass, Target } from "lucide-react";
import { company, platforms, regions, opportunities, insights, operatingModel } from "@/lib/data";
import ContactForm from "@/components/contact-form";

export const metadata: Metadata = {
  alternates: { canonical: "/" },
};

export default function Home(){
 return <>
  <section className="relative overflow-hidden">
   <Image src="/Fundo.webp" alt="" fill priority className="object-cover object-right"/>
   <div className="absolute inset-0 bg-gradient-to-r from-[#061826] via-[#061826]/90 to-[#061826]/30"/>
   <div className="container relative pt-10 pb-16 md:pt-14 md:pb-20">
    <div className="max-w-3xl"><p className="eyebrow !text-gold text-center justify-center">U.S.-anchored · Global reach · Established {company.founded}</p><h1 className="display mt-5 text-5xl md:text-7xl leading-[.96] text-white max-w-4xl">Connecting U.S. capital to global growth markets.</h1><p className="mt-7 text-lg md:text-xl leading-8 text-slate-300 max-w-2xl">{company.summary}</p><div className="mt-9 flex flex-row gap-3"><Link href="#opportunities" className="btn btn-dark flex-1 sm:flex-none text-center whitespace-nowrap px-3 sm:px-5"><span className="sm:hidden">Explore</span><span className="hidden sm:inline">Explore opportunities</span> <ArrowRight className="ml-2 h-4 w-4 shrink-0"/></Link><Link href="#contact" className="btn btn-light flex-1 sm:flex-none text-center whitespace-nowrap px-3 sm:px-5"><span className="sm:hidden">Partner</span><span className="hidden sm:inline">Partner with ANCAPA</span></Link></div><div className="mt-10 text-sm tracking-[.18em] uppercase text-slate-400">Africa <span className="mx-2">•</span> Caribbean <span className="mx-2">•</span> Southeast Asia</div></div>
   </div>
  </section>

  <section id="about" className="container py-14 md:py-16"><div className="grid lg:grid-cols-[.85fr_1.15fr] gap-14 items-start">
    <div>
      <p className="eyebrow">About ANCAPA</p>
      <h2 className="display text-4xl md:text-5xl text-navy mt-4">One platform from origination to execution.</h2>
      <p className="mt-6 text-lg leading-8 text-slate-600">ANCAPA Global Partners combines U.S. market access with grounded execution capabilities in emerging and frontier economies. We focus on commercially relevant sectors where capital, technology and strategic assets intersect.</p>
      <div className="mt-8 grid grid-cols-3 gap-4 max-w-md">
        {[[company.founded,"Founded"],[platforms.length,"Platforms"],[regions.length,"Regions"]].map(([v,l])=><div key={l as string} className="border-l-2 border-gold pl-3"><div className="display text-2xl text-navy">{v}</div><div className="text-xs text-slate-500 mt-1">{l}</div></div>)}
      </div>
      <Link href="/about" className="chip mt-8 w-fit text-navy">Learn more about ANCAPA <ArrowRight className="h-4 w-4"/></Link>
    </div>
    <div className="grid sm:grid-cols-2 gap-4">
      {[[Compass,"U.S.-anchored origination","Direct access to investors, sponsors and strategic capital based in the United States."],[Handshake,"Cross-border partnerships","Structured relationships with governments, corporates and operating partners across focus markets."],[MapPinned,"Local intelligence","On-the-ground execution support and market intelligence in every region we serve."],[Target,"Disciplined development","Commercially grounded project development from origination through execution."]].map(([Icon,title,text]:any)=><div key={title} className="card p-6"><div className="h-11 w-11 rounded-xl bg-navy/5 text-navy flex items-center justify-center"><Icon className="h-5 w-5"/></div><h3 className="mt-5 font-semibold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}
    </div>
  </div></section>

  <section id="platforms" className="bg-[#f7f5ef]"><div className="container py-14 md:py-16"><div className="max-w-3xl"><p className="eyebrow">Our platform</p><h2 className="display text-4xl md:text-5xl text-navy mt-4">Five capabilities. One global platform.</h2><p className="mt-5 text-slate-600 text-lg">A single institutional brand designed to move from opportunity identification to capital formation and execution.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-6 gap-5 mt-12">{platforms.map((p,i)=>{const span=i<2?"lg:col-span-3":"lg:col-span-2"; return <Link href={`/platforms/${p.slug}`} key={p.slug} className={`card p-7 min-h-[300px] flex flex-col hover:-translate-y-1 transition bg-white ${span}`}><div className="h-16 flex items-center"><Image src={p.logo} alt={p.name} width={200} height={80} className="h-14 w-auto object-contain object-left"/></div><h3 className="mt-6 text-xl font-semibold text-navy">{p.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{p.description}</p><span className="chip mt-auto w-fit text-navy">Explore <ArrowRight className="h-4 w-4"/></span></Link>})}</div></div></section>

  <section id="model" className="bg-[#071c2c] text-white"><div className="container py-14 md:py-16"><div className="grid lg:grid-cols-[.8fr_1.2fr] gap-14"><div><p className="eyebrow !text-gold">How we work</p><h2 className="display text-4xl md:text-5xl mt-4">From market intelligence to investable execution.</h2><p className="mt-6 text-slate-300 leading-8">Our operating model is built to reduce the gap between promising projects and capital-ready opportunities.</p></div><div className="grid sm:grid-cols-2 gap-4">{operatingModel.map((m,i)=><div key={m.step} className={`border border-white/10 rounded-2xl p-6 bg-white/[.03] ${i===4?'sm:col-span-2':''}`}><div className="text-gold text-xs tracking-[.2em]">{m.step}</div><h3 className="mt-4 font-semibold text-lg">{m.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{m.text}</p></div>)}</div></div></div></section>

  <section id="markets" className="container py-14 md:py-16"><div className="flex flex-col md:flex-row md:items-end justify-between gap-6"><div><p className="eyebrow">Growth corridors</p><h2 className="display mt-3 text-4xl md:text-5xl text-navy">Markets where capital meets scale.</h2></div><Link href="/markets" className="chip text-navy group">View market strategy <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link></div><div className="grid md:grid-cols-3 gap-5 mt-10">{regions.map((r,i)=>{const Icon=[Network,ShieldCheck,TrendingUp][i]; return <Link href="/markets" key={r.name} className="group relative overflow-hidden rounded-3xl p-8 min-h-[360px] flex flex-col text-white transition hover:-translate-y-1.5 border border-white/10 shadow-[0_20px_50px_-25px_rgba(8,35,58,.6)] hover:shadow-[0_28px_60px_-20px_rgba(8,35,58,.55)]" style={{background:`radial-gradient(circle at ${20+i*30}% 15%, rgba(185,151,88,.35), transparent 45%), linear-gradient(160deg, #0e3555, #061826 75%)`}}><span className="display absolute -top-6 right-3 text-[7.5rem] leading-none text-white/[.07] select-none">0{i+1}</span><Icon className="relative h-7 w-7 text-gold"/><div className="relative mt-auto"><h3 className="display text-3xl mt-3">{r.name}</h3><p className="mt-4 text-sm leading-6 text-slate-300">{r.text}</p><span className="chip mt-6 w-fit text-white/90 border-white/20! bg-white/10!">Explore market <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></div></Link>})}</div></section>

  <section id="opportunities" className="bg-[#f7f5ef]"><div className="container py-14 md:py-16"><div className="flex flex-col md:flex-row justify-between gap-5"><div><p className="eyebrow">Opportunity pipeline</p><h2 className="display text-4xl md:text-5xl text-navy mt-3">Built around transactions, not presentations.</h2><p className="mt-5 text-slate-600 max-w-2xl">Selected theses and opportunities are presented at a high level. Detailed information can be shared with qualified counterparties subject to appropriate diligence and confidentiality.</p></div><Link className="btn btn-dark self-start" href="/opportunities">View all opportunities</Link></div><div className="mt-10 grid md:grid-cols-2 gap-4">{opportunities.map(o=><Link href={`/opportunities/${o.slug}`} key={o.slug} className="bg-white border border-slate-200 rounded-2xl p-6 flex justify-between gap-5 hover:shadow-lg transition"><div><div className="text-xs uppercase tracking-widest text-slate-500">{o.region} · {o.sector}</div><h3 className="mt-2 text-xl font-semibold text-navy">{o.title}</h3><p className="mt-3 text-sm text-slate-600">{o.summary}</p><p className="mt-4 text-xs font-semibold text-navy">{o.stage} · {o.ask}</p></div><span className="chip h-9 w-9 shrink-0 justify-center p-0 text-navy"><ArrowRight className="h-4 w-4"/></span></Link>)}</div></div></section>

  <section id="insights" className="container py-14 md:py-16"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Insights</p><h2 className="display text-4xl md:text-5xl text-navy mt-3">Commercial intelligence for strategic markets.</h2></div><Link href="/insights" className="chip hidden md:inline-flex text-navy">All insights <ArrowRight className="h-4 w-4"/></Link></div><div className="grid md:grid-cols-3 gap-5 mt-10">{insights.map(i=><article key={i.slug} className="card p-7"><div className="text-xs uppercase tracking-widest text-gold">{i.category}</div><h3 className="text-xl text-navy font-semibold mt-4 leading-7">{i.title}</h3><p className="text-sm leading-6 text-slate-600 mt-4">{i.excerpt}</p><div className="mt-8 text-xs text-slate-400">{i.date}</div></article>)}</div></section>

  <section id="partners" className="border-y border-slate-200"><div className="container py-20 grid md:grid-cols-3 gap-8">{[[Building,"Investors","Access curated opportunities and local execution support."],[Handshake,"Project sponsors","Shape credible investment propositions and connect with strategic capital."],[MapPinned,"Market partners","Build cross-border partnerships with grounded intelligence and execution capacity."]].map(([Icon,title,text]:any)=><div key={title} className="flex gap-5"><div className="h-11 w-11 rounded-xl bg-navy/5 text-navy flex items-center justify-center shrink-0"><Icon className="h-5 w-5"/></div><div><h3 className="font-semibold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></div>)}</div></section>

  <section id="contact" className="bg-navy text-white"><div className="container py-14 md:py-16 grid lg:grid-cols-[.8fr_1.2fr] gap-16"><div><p className="eyebrow !text-gold">Partner with ANCAPA</p><h2 className="display text-4xl md:text-5xl mt-4">Bring us the opportunity, or the capital mandate.</h2><p className="mt-6 text-slate-300 leading-8">We engage with investors, project sponsors, corporates, governments and strategic partners seeking credible pathways into our focus markets.</p><div className="mt-8 text-sm text-slate-400">{company.descriptor}</div><div className="chip mt-6 w-fit text-white/90 border-white/20! bg-white/10!"><MapPinned className="h-4 w-4"/>{company.location}</div></div><div className="bg-white rounded-3xl p-6 md:p-8 text-slate-900"><ContactForm compact /></div></div></section>
 </>
}
